export class PoseGroup {
  static defaultProps: {
    flipMove: boolean;
  };
  constructor(...args: any[]);
  forceUpdate(callback: any): void;
  render(): any;
  setState(partialState: any, callback: any): void;
}
export class Transition {
  static defaultProps: {
    enterAfterExit: boolean;
    enterPose: string;
    exitPose: string;
    flipMove: boolean;
    preEnterPose: string;
  };
  static getDerivedStateFromProps(props: any, state: any): any;
  constructor(...args: any[]);
  forceUpdate(callback: any): void;
  removeChild(key: any): void;
  render(): any;
  setState(partialState: any, callback: any): void;
  shouldComponentUpdate(nextProps: any, nextState: any): any;
}
export default function _default(component: any): any;
export default namespace _default {
  function a(poseConfig: any): any;
  function article(poseConfig: any): any;
  function aside(poseConfig: any): any;
  function audio(poseConfig: any): any;
  function b(poseConfig: any): any;
  function blockquote(poseConfig: any): any;
  function body(poseConfig: any): any;
  function br(poseConfig: any): any;
  function button(poseConfig: any): any;
  function canvas(poseConfig: any): any;
  function caption(poseConfig: any): any;
  function circle(poseConfig: any): any;
  function cite(poseConfig: any): any;
  function clipPath(poseConfig: any): any;
  function code(poseConfig: any): any;
  function col(poseConfig: any): any;
  function colgroup(poseConfig: any): any;
  function data(poseConfig: any): any;
  function datalist(poseConfig: any): any;
  function defs(poseConfig: any): any;
  function dialog(poseConfig: any): any;
  function div(poseConfig: any): any;
  function ellipse(poseConfig: any): any;
  function em(poseConfig: any): any;
  function embed(poseConfig: any): any;
  function fieldset(poseConfig: any): any;
  function figcaption(poseConfig: any): any;
  function figure(poseConfig: any): any;
  function footer(poseConfig: any): any;
  function form(poseConfig: any): any;
  function g(poseConfig: any): any;
  function h1(poseConfig: any): any;
  function h2(poseConfig: any): any;
  function h3(poseConfig: any): any;
  function h4(poseConfig: any): any;
  function h5(poseConfig: any): any;
  function h6(poseConfig: any): any;
  function head(poseConfig: any): any;
  function header(poseConfig: any): any;
  function hgroup(poseConfig: any): any;
  function hr(poseConfig: any): any;
  function i(poseConfig: any): any;
  function iframe(poseConfig: any): any;
  function image(poseConfig: any): any;
  function img(poseConfig: any): any;
  function input(poseConfig: any): any;
  function label(poseConfig: any): any;
  function legend(poseConfig: any): any;
  function li(poseConfig: any): any;
  function line(poseConfig: any): any;
  function linearGradient(poseConfig: any): any;
  function mask(poseConfig: any): any;
  function nav(poseConfig: any): any;
  function object(poseConfig: any): any;
  function ol(poseConfig: any): any;
  function option(poseConfig: any): any;
  function p(poseConfig: any): any;
  function param(poseConfig: any): any;
  function path(poseConfig: any): any;
  function pattern(poseConfig: any): any;
  function picture(poseConfig: any): any;
  function polygon(poseConfig: any): any;
  function polyline(poseConfig: any): any;
  function pre(poseConfig: any): any;
  function progress(poseConfig: any): any;
  function q(poseConfig: any): any;
  function radialGradient(poseConfig: any): any;
  function rect(poseConfig: any): any;
  function section(poseConfig: any): any;
  function select(poseConfig: any): any;
  function span(poseConfig: any): any;
  function stop(poseConfig: any): any;
  function strong(poseConfig: any): any;
  function svg(poseConfig: any): any;
  function table(poseConfig: any): any;
  function tbody(poseConfig: any): any;
  function td(poseConfig: any): any;
  function text(poseConfig: any): any;
  function textarea(poseConfig: any): any;
  function tfoot(poseConfig: any): any;
  function th(poseConfig: any): any;
  function thead(poseConfig: any): any;
  function time(poseConfig: any): any;
  function title(poseConfig: any): any;
  function tr(poseConfig: any): any;
  function tspan(poseConfig: any): any;
  function ul(poseConfig: any): any;
  function video(poseConfig: any): any;
}
